# Zshrc
if [[ -d ~/.zsh.d ]]; then 
  source ~/.zsh.d/zinit.zsh
  source ~/.zsh.d/settings.zsh
  source ~/.zsh.d/plugins.zsh
  source ~/.zsh.d/aliases.zsh
fi

# Autocomplete
autoload -U +X bashcompinit
autoload -U +X compinit
#autoload -Uz compinit 
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i && bashcompinit -i
else
  compinit -C -i && bashcompinit -C -i
fi

if [[ -d $HOME/.asdf ]]; then source $HOME/.asdf/asdf.sh && source $HOME/.asdf/completions/asdf.bash; fi # ASDF
if [[ -f $(which kubectl) ]]; then source <(kubectl completion zsh); fi                                  # Kubectl
if [[ -d $HOME/.krew/bin ]]; then export PATH="$PATH:$HOME/.krew/bin"; fi                                # Krew
if [[ -f $(which helm) ]]; then source <(helm completion zsh); fi                                        # Helm
if [[ -f $(which terraform) ]]; then complete -o nospace -C $(which terraform) terraform; fi             # Terraform
if [[ -f $(which aws) ]]; then complete -C "$HOME/bin/aws_completer" aws; fi                             # AWS
if [[ -f $(which az) ]]; then source /etc/bash_completion.d/azure-cli; fi                                # Azure
if [[ -f $(which gcloud) ]]; then; source /etc/bash_completion.d/gcloud; fi                              # Google