#!/bin/bash

for i in  'cm' 'ds' 'cronjobs'  \
          'deploy' 'ingresses' 'jobs' \
          'limitranges' 'pvc' 'resourcequotas' \
          'secrets' 'sa' 'svc' 'statefulsets' \
          'role', 'rolebinding' \
          'clusterrole', 'clusterrolebinding';
do
  /usr/local/bin/kubectl get $i --all-namespaces --export -o=custom-columns=NM:.metadata.namespace,RSRC:.kind,NAME:.metadata.name | grep -v '^NM' ;
done > $BCKFILE

for i in  'pv' 'ns';
do
  /usr/local/bin/kubectl get $i --export -o=custom-columns=RSRC:.kind,NAME:.metadata.name | grep -v '^RSRC' ;
done > $ADMBCK

awk '{print "/usr/local/bin/kubectl get -n="$1" "$2" "$3" -o yaml > "$1"-"$2"-"$3".yaml"}' $BCKFILE > $TMPFILE
awk '{print "/usr/local/bin/kubectl get "$1" "$2" -o yaml > "$1"-"$2".yaml"}' $ADMBCK >> $TMPFILE

bash $TMPFILE
rm $TMPFILE

tar cvfz $CLUSTER-$DATE.tar.gz $CLUSTER/$DATE
mv $HOMEPATH/$CLUSTER-$DATE.tar.gz $ARCHIVE
